OBJS=main.o sum.o

CFLAG=-I.

SumTest:$(OBJS)
	g++ -o SumTest $(OBJS)



# SumTest:$(OBJS)
# 	g++ -o SumTest $(OBJS)
# main.o:main.cpp sum.h
# 	g++ -c main.cpp
# sum.o:sum.cpp sum.h
# 	g++ -c sum.cpp
clean:
	rm SumTest $(OBJS)